name: dev_base_url_example
description: Example app for dev_base_url package.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  dev_base_url:
    path: ../
